name: Provision Github Repo

on:
  push:
    branches:
      - main

jobs:
  provision:
    name: Github repo create
    runs-on: ubuntu-latest

  steps:
    - name: Install Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.2.3

    - name: Terraform Format
      id: fmt
      run: terraform fmt

    - name: Terraform Init
      id: init
      run: terraform init

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color

    - name: Terraform Plan
      id: validate
      run: terraform plan -no-color

    - name: Terraform Apply
      id: validate
      run: terraform apply -no-color